### ISSUE TITLE
Perfect pixel 2

### ISSUE THREAD

**Issue by FanManutd** [Nurvive/MetaLamp-2-step#27]
Добавь пожалуйста в проект папку со скринами макета, с которыми ты сверял perfect pixel.

**Comment by FanManutd** [comment]
Есть много расхождений с perfect pixel, проверь на всех страницах пожалуйста
![image](https://user-images.githubusercontent.com/90761929/162950818-54f60a6e-453f-49dc-8e4a-dc06a36fdf4b.png)
![image](https://user-images.githubusercontent.com/90761929/162951211-0be3a5e2-0b1c-42ef-b62e-4e2d8c3dec3a.png)
Где-то лишний пиксель в чекбоксе есть. 
![image](https://user-images.githubusercontent.com/90761929/162951848-2b78df93-78cc-41e5-9686-22ae8b4725b8.png)
Вот тут явная проблема 
![image](https://user-images.githubusercontent.com/90761929/162952018-90b6f49a-fe7e-413e-81d6-88e413e77bc4.png)

**Comment by Nurvive** [comment]
![login](https://user-images.githubusercontent.com/55381410/163196990-b2cd86e7-88d5-469e-bae0-5ce7f904e579.PNG)
![Registration](https://user-images.githubusercontent.com/55381410/163196998-7dc3f252-48ca-4c60-9cf6-993c5819729a.PNG)
Вот здесь странное поведение, обе карточки по 380px и им задано `margin: 0 auto`, также их родители одинаковой ширины, но карточка регистрации почему-то съезжает на 2 пикселя. Очень важна битва за 2 пикселя или можно так оставить?

**Comment by FanManutd** [comment]
> Очень важна битва за 2 пикселя или можно так оставить?

Можно оставить

**Comment by FanManutd** [comment]
Теперь гораздо лучше)

На странице landing контент должен находится в тех же границах, как это сделано на других страницах
![image](https://user-images.githubusercontent.com/90761929/163677171-212954a9-f3bb-48ce-9c10-c6854e0f0f47.png)

**Comment by Nurvive** [comment]
У меня на этой странице все окей, только текст чуть-чуть съехал, это я поправлю
![image](https://user-images.githubusercontent.com/55381410/163682774-4663d8f5-fe6b-4c7f-ae1a-63f598cab8ed.png)

**Comment by FanManutd** [comment]
> У меня на этой странице все окей

Ты уверен? Как-то странно, у меня во всех браузерах как на скрине ниже. 
![image](https://user-images.githubusercontent.com/90761929/163769927-1cc35802-9ab7-45ed-9aec-5bbf1a007875.png)

**Comment by Nurvive** [comment]
Вы имеете ввиду, что карточка и текст должны находиться на одинаковом расстоянии при размере экрана больше 1440px?

**Comment by FanManutd** [comment]
> Вы имеете ввиду, что карточка и текст должны находиться на одинаковом расстоянии при размере экрана больше 1440px?

Ага. На других же страницах контент ограничен 1440 пикселями, здесь тоже должен.
