### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by FanManutd** [Nurvive/MetaLamp-2-step#28]
### Папка pug
Папка pug явно лишняя. Название подразумевает содержание pug файлов, но в ней много того, что к pug никак не относится. Можно просто вынести папки blocks, pages, templates в src.

### Инициализация компонентов
Сейчас почти весь js компонентов инициализируется в init.js, при этом компонент `dropdown` вообще живёт своей жизнью, и инициализируется самостоятельно. Также файл init.js ищет компоненты по внутреннему css-классу компонента, то есть знает его внутреннее устройство, что является нарушением инкапсуляции. Также у такого подхода появится проблема, когда один и тот же компонент захочется инициализировать несколько раз с разными параметрами в js. 

Что бы избавиться от этих проблем, можно использовать следующий подход. У нас есть страницы, которые подключают у себя какие-то компоненты. Пусть у каждой страницы будет свой класс. Внутри этого класса страница будет искать родителей нужных ей компонентов и инициализировать компоненты, передавая каждому своего родителя. Компонент получая родителя, будет искать внутри него всё необходимое. 
Так как у тебя одна точка входа, тогда в файле init.js можно инициализировать классы страниц. 

Таким образом, никто и ничто не будет знать о внутреннем устройстве компонентов, на страницах будут подключаться только те компоненты, которые там используются.

**Comment by Nurvive** [comment]
1. В файле init.js при инициализации класса страницы корневой элемент передается извне или класс знает его изначально?
2. Класс страницы должен инициализировать и Header тоже?

**Comment by FanManutd** [comment]
1. Здесь не критично. Пусть передаётся извне.
2. Да.

**Comment by FanManutd** [comment]
1. Страницы до сих пор знают о внутренних классах компонентов. Как я говорил выше, компоненты должны получать своего родителя. 
![image](https://user-images.githubusercontent.com/90761929/162943111-547dd9f7-b0bc-45ce-9d47-d3326f843aaa.png)
2. Так же есть случаи неявных зависимостей между компонентами в js. Например, компонент `comment` использует компонент `like-button`, но `like-button` инициализируется на странице, а не в компоненте. То есть, если убрать со страницы `like-button`, компонент `comment` сломается. `comment` должен инициализировать `like-button`.

**Comment by Nurvive** [comment]
Всё-таки не совсем понял про инициализацию, типа так:
`init() {
        new Header(element, this.root.parent());
        new Canvas(element, this.root);
....
    }`
?

**Comment by FanManutd** [comment]
На примере компонента `canvas`. Ты сейчас передаёшь в компонент его же собственный элемент `.js-canvas__area`. Элемент, который принадлежит компоненту. Откуда страница может знать о внутренности компонента? Она не должна об этом знать. 

Передавай в компонент родительский элемент, к которому он подключается (см. скрин). То есть страница говорит компоненту "я подключила тебя вот на этот элемент, это твой родитель". А компонент уже в своём родителе ищет всё что ему необходимо. 
![image](https://user-images.githubusercontent.com/90761929/163190778-9287ef6d-450e-4d8a-a0e9-9d83bfd217a1.png)
