### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by FanManutd** [Nurvive/MetaLamp-2-step#30]
### Dropdown
Твой `dropdown` захардкожен на 2 конкретных поведения. С комнатами и гостями. Как насчёт сделать его универсальным? Смотри, у нас есть список элементов, которые он принимает. Каждый элемент списка - это 3 варианта слова с разными окончаниями, минимальное, максимальное и текущее значение. Также у дропдауна есть 2 варианта вывода результата. 
1й вариант - вывод суммы всех значений с каким-то ключевым словом с 3мя разными окончаниями (1 фрукт/2 фрукта/5 фруктов). 
2й вариант - вывод значения и элемента списка через запятую (2 апельсина, 1 мандарин). 
Вот и всё) Можешь погуглить функцию формирования окончания в зависимости от числа.

**Comment by FanManutd** [comment]
Я не просто так написал про минимальные и максимальные значения) Надо добавить возможность ограничивать значения. Если пользователь сможет выбрать 15 спален и 10 младенцев, это странно)

**Comment by FanManutd** [comment]
### Dropdown
1. Из названия переменной `obj` непонятно, что в ней хранится. 
2. Если в переменной хранится какой-то список, это должно быть отображено в названии переменной. Либо использовать множественное число, либо слово, подразумевающее несколько элементов. 
3. В best-practices есть требование, что бы у каждого элемента, который ищется в js был префикс js- [5.1](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#5.1). Здесь нет необходимости искать по вложенным p или div. К слову `dropdown-item` выглядит как неотъемлемая часть `dropdown`. Думаю можно папку с `dropdown-item` перенести внутрь папки `dropdown`.
![image](https://user-images.githubusercontent.com/90761929/162949561-6c0bb393-a349-47ba-b4c6-d5391aa2527b.png)
4. Разве в дропдауне может быть несколько кнопок "очистить" или "применить"?

Каково назначение этого метода? Вызов `e.stopPropagation()` плохая и опасная практика. Опиши проблему, я могу помочь с более красивым решением. 
![image](https://user-images.githubusercontent.com/90761929/162953356-3ee7191b-e8ae-40a2-8afd-1d65a4c32c6b.png)

Правилом `no-new` можно пренебречь, добавить в игнор. Иначе `return` в пустоту может легко запутать. Такие же случаи нашёл в DateDropdown, может ещё где-то есть. 
![image](https://user-images.githubusercontent.com/90761929/162965069-73699ca3-03d1-4125-a4ff-87b832260173.png)

**Comment by Nurvive** [comment]
3. Почему нет необходимости искать по вложенным p или div? В случае с дивами, я же ищу не просто по тэгу, а по дата-атрибуту

**Comment by FanManutd** [comment]
> Почему нет необходимости искать по вложенным p или div? В случае с дивами, я же ищу не просто по тэгу, а по дата-атрибуту

Ты же ищешь конкретный html-элемент. Задай ему js- класс и ищи по нему. Зачем вложенности?) Например `.js-dropdown-item__minus`.

**Comment by FanManutd** [comment]
1.Полагаю необходимости в `data-type` больше нет)
![image](https://user-images.githubusercontent.com/90761929/163676922-70e009f9-ee42-4332-b8e6-0460c0592d12.png)

2.Какое-то непонятное и не нужное сокращение.
![image](https://user-images.githubusercontent.com/90761929/163677256-a9217f46-8669-45a0-840d-f91bd794a732.png)

3. А зачем здесь использовать самовызывающуюся функцию? Перенеси в метод класса и вызови метод. 
![image](https://user-images.githubusercontent.com/90761929/163677320-ccdae770-5d69-442a-8c44-735cf6f1f2a1.png)

4. Имена функций/методов должны начинаться с глаголов. В данном случае достаточно поставить слово `create` первым. 
![image](https://user-images.githubusercontent.com/90761929/163677499-87e831a6-3e0d-4e96-a42a-92808bac8809.png)

5. Сейчас у параметра `defaultWords` в `dropdown` неочевидная и сложная структура в виде массива, где каждый чётный элемент - это слово, а каждый нечётный - массив с 3мя значениями. Пусть defaultWords будет массивом объектов. Каждый объект имеет свойства `word`, `min`, `max`, `current`. И передавать параметры будет удобней, и код самого dropdown-а будет более читабельным.
![image](https://user-images.githubusercontent.com/90761929/163677900-dcc65560-121a-4914-adf6-a8308e5186c7.png)

6. Здесь из объекта `event` используется только единственное свойство, можно передать ведь только его, а не целый объект. Это же касается других методов.
![image](https://user-images.githubusercontent.com/90761929/163677953-6120a4f5-cd7c-4db9-bd25-ad681499c1dd.png)

7. `handleDocumentClick`.
![image](https://user-images.githubusercontent.com/90761929/163678069-53d027b9-744c-4e7b-b990-606fd37382a9.png)

8. Осмысленные названия 
![image](https://user-images.githubusercontent.com/90761929/163678334-41a2fab6-330f-4bf3-a083-9ca7b4dfe513.png)

9. Файл `Dropdown.js` с большой буквы и файл `FindRoom.js` надо в kebab-case формате.
![image](https://user-images.githubusercontent.com/90761929/163679031-a8ffbc08-c317-4d4c-9e20-30f76707e41f.png)

10. Все jQuery переменные должны начинаться со знака `$` [JS 5.3](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.3). Так же от двух переменных с одинаковым названием надо избавиться. 
![image](https://user-images.githubusercontent.com/90761929/163679729-c33b923b-9c66-4d42-8a6d-24dd39e52122.png)

**Comment by FanManutd** [comment]
Зачем тут `let val`, когда можно объявить её по месту использования через `const`?
![image](https://user-images.githubusercontent.com/90761929/163680368-57a417b6-4add-49a5-8a5d-52430590b4a1.png)

**Comment by Nurvive** [comment]
9. А разве нет исключения, что файл экспортирующий класс должен быть в CamelCase?

**Comment by FanManutd** [comment]
> А разве нет исключения, что файл экспортирующий класс должен быть в CamelCase?

Ага, есть, просто у тебя некоторые файлы в kebab-case, хотя тоже экспортируют класс. Просто приведи в единый вид.

**Comment by FanManutd** [comment]
1. Пусть `this.restrictions` будет массив объектов, а не массив массивов. Тогда вместо `restrictions[index][0]` можно будет писать `restrictions[index].min/max/current`, что гораздо лучше читается. 
![image](https://user-images.githubusercontent.com/90761929/164238477-7b036a0d-be8b-4b13-b6a5-d6b18581d658.png)

2. `bigValue` и `smallValue` - не осмысленные названия) 
![image](https://user-images.githubusercontent.com/90761929/164238897-7a2e30d7-3e8a-40b0-8c1b-ba550a7cacfd.png)

3. Не нужная самовызывающаяся функция. Кстати в SideMenu лучше передавать непосредственно сам HTML-элемент, а не класс по которому его надо искать.
![image](https://user-images.githubusercontent.com/90761929/164239596-52816eee-9abd-4962-b45f-7aca7625e2d8.png)
