### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by FanManutd** [Nurvive/MetaLamp-2-step#32]
1. Вроде массив, а вроде и obj)
![image](https://user-images.githubusercontent.com/90761929/162956342-d6947bf9-b7c8-4a39-88a6-8c1d09624c41.png)
2. Можно использовать деструктуризацию 
![image](https://user-images.githubusercontent.com/90761929/162962320-afb3457d-1293-4b30-9024-18ec0bc09bd0.png)
3. Как-то странно здесь использовать имя класса в отрыве от блока. По моему в этом нет необходимости. 
![image](https://user-images.githubusercontent.com/90761929/162962620-ad5e3478-8194-46be-a6a7-a7e9657b9724.png)
4. Переменная text, а в ней массив
![image](https://user-images.githubusercontent.com/90761929/162965250-32ec2724-d33f-4039-9f50-2c3d0940b767.png)

**Comment by FanManutd** [comment]
1.Класс с приставкой `js-` должен дублировать уже существующий класс, тут его нет. 
![image](https://user-images.githubusercontent.com/90761929/163676788-a703a011-4839-4fe8-82e6-6860a6fa5121.png)

2.Элементы футера, так же как и у хэдера должны приходить параметрами.

3.`options` как-то плохо подходит. Может лучше `menu` или `navigatoin`?
![image](https://user-images.githubusercontent.com/90761929/163679136-34e925f1-0afd-473a-a51e-bcb286cdfa48.png)

4. Почему закоменчен?
![image](https://user-images.githubusercontent.com/90761929/163679818-0f6d1131-2e5e-45f1-9256-6d06ab7c24bd.png)

5. Что такое `pros`?
![image](https://user-images.githubusercontent.com/90761929/163679858-9106bf37-d00f-4f3e-8fde-4de97d99edb7.png)

**Comment by Nurvive** [comment]
4. Если включить сразу два хедера, то боковые меню накладываются друг на друга и некорректно работают, а так как в реальном проекте на одной странице не будет два хедера, то здесь я один закомментил, чтобы можно было быстро посмотреть другой вид хедера.
5. Этоn элемент
![image](https://user-images.githubusercontent.com/55381410/163682684-7528f09a-1a08-407d-bcae-e89ea330623b.png)
