### ISSUE TITLE
Повторяющийся код

### ISSUE THREAD

**Issue by osyka-yuri** [Nurvive/MetaLamp-2-step#33]
https://github.com/Nurvive/MetaLamp-2-step/blob/ddc7d9da964d8bcd66fc0d4e6465fc9d05d72970/src/blocks/date-dropdown/date-dropdown.pug#L3-L29
Здесь несколько раз повторяется один и тот же кусок кода, чтобы этого избежать можно использовать цикл.

**Comment by osyka-yuri** [comment]
https://github.com/Nurvive/MetaLamp-2-step/blob/6f1e0c71ee0252892a2e709350a3d09e2f243084/src/blocks/date-dropdown/date-dropdown.pug#L8-L26
Все еще присутствует повторяющийся код, отличие только в data атрибутах и в разном значении переменной className, значения data атрибутов можно назначаться как-то так data-double=`${type === 'double'}`, значение переменной можно отдельно назначить.

**Comment by osyka-yuri** [comment]
https://github.com/Nurvive/MetaLamp-2-step/blob/6f1e0c71ee0252892a2e709350a3d09e2f243084/src/blocks/canvas/canvas.pug#L7-L14
Здесь повторяется span.canvas__word, можно создать функцию и результат ее уже использовать в качестве значения, вынести ее можно к примеру в папку utils, тем более эта функция еще нужна в dropdown.

**Comment by Nurvive** [comment]
> Здесь повторяется span.canvas__word, можно создать функцию и результат ее уже использовать в качестве значения, вынести ее можно к примеру в папку utils, тем более эта функция еще нужна в dropdown.

Вроде в паге нет импорта js-функций, да и вообще функций извне, поэтому пришлось копировать функцию в миксин

**Comment by osyka-yuri** [comment]
В pug если что можно тоже импортировать функции `const ending = require(path);`
