### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by osyka-yuri** [Nurvive/MetaLamp-2-step#36]
Сейчас у кнопок ограниченна ширина, подобного лучше не делать, так как текст может быть разным, и какой-то длинный текст может просто не влезть, ширина должна подстраиваться под текст, размер кнопок лучше контролировать с помощью padding.

---

И так же сейчас можно создать только кнопку, в дизайне кнопки и ссылки имеет одни и те же стили, должна быть возможность создать как ссылку, так и кнопку. Можно к примеру как-то так:
```
const tag = type === 'link' ? 'a' : 'button';
const buttonType = !(type === 'link') && type

#{tag}(class=classes, type=buttonType)= text
        if (withArrow)
            span.button__arrow
```

**Comment by Nurvive** [comment]
> Сейчас у кнопок ограниченна ширина, подобного лучше не делать, так как текст может быть разным, и какой-то длинный текст может просто не влезть, ширина должна подстраиваться под текст, размер кнопок лучше контролировать с помощью padding.

Тогда с разным текстом у кнопок разная ширина, а в макете одинаковая, как быть?
